obj-y += setup.o fault.o fault.asm.o e820.o rtc.o stacktrace.o
obj-y += isrc_s.o idt.o lapic.o
obj-y += head_32c_s.o head_32.o
obj-y += atomic.o barrier.o spinlock.o
obj-y += linker.lds
subdir-y += sched/