#ifndef _GLOBAL_CONFIG_H
#define _GLOBAL_CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define USER_CODE_SEGMENT 0x1b
#define USER_DATA_SEGMENT 0x23

#define TOTAL_GDT_SEGMENTS 6
#define TOTAL_INTERRUPTS 256
#define TIMER_FREQUENCY 20

#define SYSCALLS_MAX 32

// Memory

#define KiB(x) (x * 1024u)
#define MiB(x) (x * KiB(1024u))

#define _TEMP_PAGE_DIRECTORY_ADDRESS 0x02000000

#define HEAP_SIZE_BYTES MiB(40)
#define HEAP_BLOCK_SIZE 4096

#define HEAP_PHYS_BASE 0x01000000
#define HEAP_PHYS_END  (HEAP_PHYS_BASE + HEAP_SIZE_BYTES)

#define HEAP_VIRT_BASE 0xC2000000
#define HEAP_VIRT_END  (HEAP_VIRT_BASE + HEAP_SIZE_BYTES)

#define HEAP_TABLE_PHYS_BASE 0x00007E00
#define HEAP_TABLE_PHYS_END  (HEAP_TABLE_PHYS_BASE + (HEAP_SIZE_BYTES / HEAP_BLOCK_SIZE))

#define HEAP_TABLE_VIRT_BASE \
	(HEAP_VIRT_BASE - (HEAP_TABLE_PHYS_END - HEAP_TABLE_PHYS_BASE))

#define HEAP_TABLE_VIRT_END (HEAP_TABLE_VIRT_BASE + (HEAP_SIZE_BYTES / HEAP_BLOCK_SIZE))

#define KERNEL_FB_VIRT_BASE 0xD0000000

#define KERNEL_STACK_SIZE KiB(512)
#define KERNEL_STACK_PHYS_TOP 0x00200000
#define KERNEL_STACK_PHYS_BOTTOM (KERNEL_STACK_PHYS_TOP - KERNEL_STACK_SIZE)

#define KERNEL_STACK_VIRT_TOP 0xC1000000
#define KERNEL_STACK_VIRT_BOTTOM (KERNEL_STACK_VIRT_TOP - KERNEL_STACK_SIZE)

#define KERNEL_PHYS_BASE 0x00100000
#define KERNEL_VIRT_BASE 0xC0000000

// Files and File System
#define PATH_MAX 128
#define FILE_DESCRIPTORS_MAX 64
#define FILESYSTEMS_MAX 8
#define DEVICES_MAX 8

// Process Management
#define PROC_MAX 32
#define PROC_NAME_MAX 32
#define PROC_ARG_MAX 32
#define PROC_ENV_MAX 32
#define PROC_FD_MAX 16
#define PROC_VIRTUAL_ADDRESS 0x400000
#define PROC_VIRTUAL_STACK_START 0x3FF000
#define PROC_STACK_SIZE 8192
#define PROC_KERNEL_STACK_SIZE 4096
#define PROC_VIRTUAL_STACK_END PROC_VIRTUAL_STACK_START - PROC_STACK_SIZE

#endif
