#!/usr/bin/env python3
import sys
import subprocess

def main():
    if len(sys.argv) < 3:
        print("Usage: gen_kallsyms.py <elf_file> <output_c_file> [nm_bin]")
        sys.exit(1)
        
    elf_file = sys.argv[1]
    out_file = sys.argv[2]
    nm_bin = sys.argv[3] if len(sys.argv) > 3 else "nm"
    
    cmd = [nm_bin, "-n", elf_file]
    res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, check=True)
    
    symbols = []
    for line in res.stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) >= 3:
            addr_str, sym_type, name = parts[0], parts[1], parts[2]
            try:
                addr = int(addr_str, 16)
            except ValueError:
                continue
            
            # Filter for kernel virtual memory addresses (>= 0xC0000000)
            # Filter function/text symbols: T, t, W, w
            if addr >= 0xC0000000 and sym_type in ['T', 't', 'W', 'w']:
                if not name.startswith("kallsyms_"):
                    symbols.append((addr, name))
                    
    symbols.sort(key=lambda x: x[0])
    
    with open(out_file, "w") as f:
        f.write("/* Auto-generated by gen_kallsyms.py - DO NOT EDIT */\n")
        f.write("#include <kernel/kallsyms.h>\n\n")
        f.write("const struct kallsym_entry kallsyms_names[] = {\n")
        for addr, name in symbols:
            f.write(f'    {{ 0x{addr:08X}UL, "{name}" }},\n')
        f.write("};\n\n")
        f.write(f"const size_t kallsyms_num_symbols = {len(symbols)};\n")

if __name__ == "__main__":
    main()
