src := $(srctree)/$(obj)

obj-y :=
subdir-y :=
target :=
subdir-asflags-y :=
subdir-ccflags-y :=

relocable := y

-include $(src)/Makefile

ifeq ($(target),)
    target := $(OBJ_DIR)/$(obj)built-in.o
endif

relocflag :=
ifeq ($(relocable), y)
    relocflag += -r
endif

KBUILD_AFLAGS += $(subdir-asflags-y)
KBUILD_CFLAGS += $(subdir-ccflags-y)

subdir-y := $(sort $(subdir-y) $(patsubst %/,%/, $(filter %/, $(obj-y))))
obj-y := $(filter-out %/, $(obj-y))

# Map the short file names before prepending $(OBJ_DIR)
DEPS := $(patsubst %.o,$(OBJ_DIR)/$(obj)%.d,$(filter %.o,$(obj-y)))

# Prepend build folder to objects
subdir-obj := $(foreach dir, $(subdir-y), $(obj)$(dir)built-in.o)
obj-y := $(addprefix $(OBJ_DIR)/$(obj), $(obj-y))
subdir-files := $(addprefix $(OBJ_DIR)/, $(subdir-obj))

# Compile rules
$(OBJ_DIR)/$(obj)%.o: $(src)%.c
	@echo "  CC         $<"
	@mkdir -p $(dir $@)
	$(Q)$(CC) $(KBUILD_CFLAGS) -MMD -MP -c $< -o $@

$(OBJ_DIR)/$(obj)%.asm.o: $(src)%.asm
	@echo "  AS         $<"
	@mkdir -p $(dir $@)
	$(Q)$(AS) $(KBUILD_ASFLAGS) -o $@ $<

$(OBJ_DIR)/$(obj)%.lds: $(src)%.lds.S
	@echo "  CPP        $<"
	@mkdir -p $(dir $@)
	$(Q)$(CPP) $(KINCLUDE) -P -U$(ARCH) -o $@ $<

$(OBJ_DIR)/$(obj)%c_s.o: $(src)%.S
	@echo "  CPP        $<"
	@mkdir -p $(dir $@)
	$(Q)$(CPP) $(KBUILD_CFLAGS) $(KINCLUDE) -MMD -MP -D__ASSEMBLY__ -P -o $(OBJ_DIR)/$(obj)$*.S $<
	@echo "  AS         $<"
	$(Q)$(AS) $(KBUILD_ASFLAGS) -o $@ $(OBJ_DIR)/$(obj)$*.S

all: $(target)

$(subdir-files): $(subdir-obj) ;

$(target): $(subdir-files) $(obj-y)
	@echo "  LD         $@"
	$(Q)$(LD) $(KBUILD_LDFLAGS) $(relocflag) -o $@ $(filter-out %.lds, $(obj-y) $(subdir-files))

.PHONY: $(subdir-obj)
$(subdir-obj):
	$(Q)$(MAKE) $(build)=$(dir $@)

-include $(DEPS)
