READY_ONLY     =  0x01
HIDDEN         =  0x02
SYSTEM         =  0x04
VOLUME         =  0x08
DIRECTORY      =  0x10
ARCHIVE        =  0x20
LONG_NAME      =  READY_ONLY | HIDDEN | SYSTEM | VOLUME
LONG_NAME_MASK =  READY_ONLY | HIDDEN | SYSTEM | VOLUME | DIRECTORY | ARCHIVE